package com.pedidos.api.sql;

public enum CrmClienteSQL {
	CONSULTA,

	INSERTA_CRM_CLIENTE;

	public String toString() {
		switch (this) {
			case CONSULTA:
				return "SELECT PROSPECTONUM, CUST_NUM, ORG_CODE, DIV_CODE, RAZONSOCIAL, RFC, RAZONCOMERCIAL, CALLEYNO, CALLEYNODOS, CALLEUNO, CALLEDOS, CP, COLONIA, MUNICIPIO, ESTADO, PAIS, TELUNO, EXTUNO, TELDOS, EXTDOS, TELTRES, EXTTRES, FAX, EXTFAX, SITIOWEB, OBTENIDO, GIRO, SECTOR, CLASIFICACION, STATUS, CAPTURISTA, FECHAALTA, MODIFICADOPOR, FECHAULMOD, TIPOEMPRESA, TIPO, NOMBRE, PATERNO, MATERNO, ASIGNADOA, ACTUALIZASTATUS, CLASIFREQ, PROMENSUAL, CLASISTATUS, FRECDIACOMPRA, ALERTA, CLASIPOTENCIAL, FECHAALERTA_INI, FECHAALERTA_FIN, OBSALERTA, DOCUMENTACION, CREDITO, TENDENCIA, FUERAZONA, OBSFUERAZONA, CUST_NUM2, MONTO, DIAS, CHEQUE, EFECTIVO, TRANSFERENCIA, DEPOSITO, CUENTAUNO, CUENTADOS, CUENTATRES, CUENTACUATRO, BANCOUNO, BANCODOS, BANCOTRES, BANCOCUATRO, CLABEUNO, CLABEDOS, CLABETRES, CLABECUATRO, RAZONSUNO, RAZONSDOS, RAZONSTRES, DOCUMENTACIONUNO, DOCUMENTACIONDOS, DOCUMENTACIONTRES, DOCUMENTACIONCUATRO, DOCUMENTACIONCINCO, DOCUMENTACIONSEIS, KM, RECOLECCION FROM CRMCLIENTE ;";

			case INSERTA_CRM_CLIENTE:
				return "INSERT INTO CRMCLIENTE ( CUST_NUM, ORG_CODE, DIV_CODE, RAZONSOCIAL, RFC, RAZONCOMERCIAL, CALLEYNO, CALLEYNODOS, CALLEUNO, CALLEDOS, CP, COLONIA, MUNICIPIO, ESTADO, PAIS, TELUNO, EXTUNO, TELDOS, EXTDOS, TELTRES, EXTTRES, FAX, EXTFAX, SITIOWEB, OBTENIDO, GIRO, SECTOR, CLASIFICACION, STATUS, CAPTURISTA, FECHAALTA, MODIFICADOPOR, FECHAULMOD, TIPOEMPRESA, TIPO, NOMBRE, PATERNO, MATERNO, ASIGNADOA, ACTUALIZASTATUS) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
		}
		return null;
	}
}
